# Pin npm packages by running ./bin/importmap

pin "application", preload: true
pin "@hotwired/turbo-rails", to: "https://ga.jspm.io/npm:@hotwired/turbo-rails@7.3.0/app/javascript/turbo/index.js"
pin "@hotwired/turbo", to: "https://ga.jspm.io/npm:@hotwired/turbo@7.3.0/dist/turbo.es2017-esm.js"
pin "@rails/actioncable/src", to: "https://ga.jspm.io/npm:@rails/actioncable@7.0.6/src/index.js"
pin "morphdom", to: "https://ga.jspm.io/npm:morphdom@2.7.0/dist/morphdom-esm.js"
pin "turbo-morphdom", to: "turbo-morphdom.js"
pin "fake_audio", to: "fake_audio.js"
pin "@hotwired/stimulus", to: "https://ga.jspm.io/npm:@hotwired/stimulus@3.2.1/dist/stimulus.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js", preload: true
pin_all_from "app/javascript/controllers", under: "controllers"
pin "@rails/request.js", to: "https://ga.jspm.io/npm:@rails/request.js@0.0.8/src/index.js"
pin "@anycable/turbo-stream", to: "https://ga.jspm.io/npm:@anycable/turbo-stream@0.3.2/index.js"
pin "@anycable/core", to: "https://ga.jspm.io/npm:@anycable/core@0.7.1/index.js"
pin "nanoevents", to: "https://ga.jspm.io/npm:nanoevents@7.0.1/index.js"
pin "@anycable/web", to: "https://ga.jspm.io/npm:@anycable/web@0.7.0/index.js"
pin "@turbo-boost/commands", to: "https://ga.jspm.io/npm:@turbo-boost/commands@0.0.11/app/assets/builds/@turbo-boost/commands.js"
pin "turbo-mount", to: "turbo-mount.js"
pin "turbo-mount/react", to: "turbo-mount/react.js"
pin "turbo-mount-initializer"
pin "react", to: "https://ga.jspm.io/npm:react@18.3.1/index.js"
pin "react-dom", to: "https://ga.jspm.io/npm:react-dom@18.3.1/index.js"
pin "react-dom/client", to: "https://ga.jspm.io/npm:react-dom@18.3.1/client.js"
pin "scheduler", to: "https://ga.jspm.io/npm:scheduler@0.23.2/index.js"
pin "react-player", to: "https://ga.jspm.io/npm:react-player@2.16.0/lib/index.js"
pin "deepmerge", to: "https://ga.jspm.io/npm:deepmerge@4.3.1/dist/cjs.js"
pin "load-script", to: "https://ga.jspm.io/npm:load-script@1.0.0/index.js"
pin "memoize-one", to: "https://ga.jspm.io/npm:memoize-one@5.2.1/dist/memoize-one.cjs.js"
pin "prop-types", to: "https://ga.jspm.io/npm:prop-types@15.8.1/index.js"
pin "react-fast-compare", to: "https://ga.jspm.io/npm:react-fast-compare@3.2.2/index.js"
pin "react-player/file", to: "https://ga.jspm.io/npm:react-player@2.16.0/file.js"
pin "react-player/youtube", to: "https://ga.jspm.io/npm:react-player@2.16.0/youtube.js"
pin "react-player/lazy", to: "https://ga.jspm.io/npm:react-player@2.16.0/lazy/index.js"
pin "react-h5-audio-player", to: "https://ga.jspm.io/npm:react-h5-audio-player@3.9.3/es/index.js"
pin "@babel/runtime/helpers/assertThisInitialized", to: "https://ga.jspm.io/npm:@babel/runtime@7.26.0/helpers/esm/assertThisInitialized.js"
pin "@babel/runtime/helpers/classCallCheck", to: "https://ga.jspm.io/npm:@babel/runtime@7.26.0/helpers/esm/classCallCheck.js"
pin "@babel/runtime/helpers/createClass", to: "https://ga.jspm.io/npm:@babel/runtime@7.26.0/helpers/esm/createClass.js"
pin "@babel/runtime/helpers/defineProperty", to: "https://ga.jspm.io/npm:@babel/runtime@7.26.0/helpers/esm/defineProperty.js"
pin "@babel/runtime/helpers/extends", to: "https://ga.jspm.io/npm:@babel/runtime@7.26.0/helpers/esm/extends.js"
pin "@babel/runtime/helpers/getPrototypeOf", to: "https://ga.jspm.io/npm:@babel/runtime@7.26.0/helpers/esm/getPrototypeOf.js"
pin "@babel/runtime/helpers/inherits", to: "https://ga.jspm.io/npm:@babel/runtime@7.26.0/helpers/esm/inherits.js"
pin "@babel/runtime/helpers/possibleConstructorReturn", to: "https://ga.jspm.io/npm:@babel/runtime@7.26.0/helpers/esm/possibleConstructorReturn.js"
pin "@iconify/react", to: "https://ga.jspm.io/npm:@iconify/react@4.1.1/dist/iconify.mjs"
